<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

    <script>

    // Promise de; then blokleri ne döndürürs döndürsün reject yada resolve,  hepsi birer promise dir.



    /// Promise de then ler aslinda icerisine 2 parameter alir. Birincisi onsuccess yani basarili ise return eder ikincisi de onerror.
    // bunun sebebi promise return etmesidir.


    // Birden cok catch kullanilabilir. mesela 2 then den sonra bu islemlerde bir hata olmasina karsin catch kullanabiliriz daha sonra then ile baska bir isleme devam edip ona sonradan catch baglayabiliriz.

    // ama bu tercih edilen bir yöntem degildir. tercih edecegimiz yöntem, tek bir then icinde hem hatayi hem resolve u yakalamak degildir. bunun yerine then ve catch ile ayri ayri yakalamaktir.

    /// Örnek:

    let promise = new Promise((resolve, reject) => {
        const maybe = Math.floor(Math.random() * 2);
        if (maybe) {
            resolve("Successful")
        }
        reject("Some error");
    });

    promise
    .then(
        (result) => {
            console.log(result);
        },          // result ve error virgül ile ayrilir
        (error) => {
            console.log(error);
        }
    );






    /////////  async in promise göre daha güzel olan bir yani:

    /// promise de bir then bloku gectikten sonra tekrar onun verisine ihtiyac duyarsak geriye dönme sansimiz yoktur. eger böyle birsey yapmak istersek global degisken atayarak yapabiliriz.
    // ancak async de bu durum cok kolaydir. istedigimiz veriye istedigimiz zaman ulasabiliriz.










    const myFunc = async () => {
        console.log("Hello world");
    };

    myFunc();
    console.log(typeof(myFunc()));
    console.log(typeof(myFunc));


    // async olarak tanimlanmis func imizi normal olarak da kullanma sansina sahibiz. yani normal bir func gibi de calisabilir. ama bize tabi ki await kullanma sansi verir.

    // type of da func yanina () koymazsak sonuc func döner. 
    // () koyarsak da object döner.



    






    /////////////// Rest:

    // burada rest api si ile bir haberlesme sözkonusu. biz sunucu ile iletisime geciyoruz. asagida bulunan komutlar ile biz sadece sunucuya talep de bulunuyoruz. o bi talepleri yerine getirir yada getirmez onu bilemeyiz.

    // backend sunucusuna, post ile talep de bulundugumuzda, sana birsey gönderiyorum bunu ekle demek.
    
    /// get /  books : tüm kitaplari getir

    // get / books/{book_id}: belirli bir kitabi getir. tek kitap bilgileri getir

    // fetch kismen güncelleme, kitabin belirli bir kismi gönderilir. put ise komple güncelleme, kitabin tamami gönderilir.

     







    //////////// Json:

    // Js object notation.
    // bütün veriler key value seklinde yazilir.
    // sayilar ve true false tirnaksiz yazilir
    // Object ten farki:  object icinde func lar tanimlayabiliyoruz ama json icinde func tanimlama sansimiz yoktur. methodlar tanimlayamayiz.


    // json placeholder   website







            ////////  fetch:


    /// https://jsonplaceholder.typicode.com/users
    // eger bu kodu calistirirsak tüm 10 kisinin bilgileri gelir. 

    // sonunda /8  koyarsak ise sadece 8 nolu id ye sahip kisinin bilgileri gelir.


    // fetch de eger parametre olarak yöntem belirtmez isek default olarak get alir.


    // const url = "https://jsonplaceholder.typicode.com/users/8";

    // fetch(url)
    // .then((response) => {
    //     console.log(response);
    // })


    // su an talep ettigimiz verinin bilgilerini console da göremiyoruz cünkü bize henüz ham halini gönderdi.

    // ancak su asamada istedigimiz json in verilerini görebilmek icin, console da network e giriyoruz. orada ctrl r ile bir güncelleme yapiyoruz ve name isimli bir veri cikiyor. bunun üzerine tikliyoruz sonraisnda response yani antwort a tikliyoruz ve icerik görünüyor.



    // cors:  sadece ayni sunucudan baglanan kisilerin veri talep edebilmesi icin olusturulmus bir güvenlik sistemidir. disaridan biri aldatma yaparak veri talep etmesin diye.






    //////  simdi ham halde olan verimizi isleyecegiz:

    // const url = "https://jsonplaceholder.typicode.com/users/8";

    // fetch(url)
    // .then((response) => {
    //     console.log(response);
    //     // console.log(response.json());
    //     // sadece console da response.json()  bize bir promise döndürür. cünkü fetch de bir promise ve then de bir promis dir.
    //     return response.json();
    // }) .then((data) => {
    //     console.log(data);
    //     console.log(data.email);
    // })

    // burada islemimiz 3 asamalidir. 1. asamada fetch ile veri cekilir. ikinci de dönüsüm yapilir. 3. asamada yazdirilir. ikinci asamada verimiz henüz anlamli degildi. verimiz 3. asamada anlamli oldu 2. de cevrilerek 3. ye aktarildi. 

    // birinci then de return demezsek undefined döner





    /// HTML status codes:
    // 200 ile baslayanlar basarili
    // 400 ile baslayanlar client error
    // 500 ile baslayanlar server error


    /// herhangi bir hata geldiginde fetch kendisini hatali olarak addetmez. ben sunucudan bir response aldim der ve kendisini basarili addeder. response in ici fetch icin önemli degil

    // mesela url in sonuna herhangi bir karakter koyup yanlis url ile deneme yapsak, bu durumda error aliriz ama bu fetch in error u degildir.

    // ama url basina www yazdik ve bu durumda fetch hic iletisime gecemedi ve gelen hata "failed fetch" oldu. yani bu kez hatayi üzerine aldi.









    /// simdi fetch imizi bir func haline dönüstürecegiz:

    const url = "https://jsonplaceholder.typicode.com/users/8";

    function usingFetch(url) {
        fetch(url)
        .then((result) => {
            console.log(result);
            if (result.status != 200) {
                throw new Error("Something went wrong!")
            }
                // 2. method:
            // if (result.ok =! true) {
            //     throw new Error("Something went wrong!")
            // }
            return result.json();
        }) .then((result2) => {
            // console.log(result2);
            return result2;
        }) .then((result3) => {
            console.log(result3);
        })
        .catch((error) => {
            console.log(error);
        })
    }

    usingFetch(url);


    /// Note: simdi burada then ler ve catch; fetch promise ine baglidir. Bu nedenle, fetch in üzerine almadigi bir error calisirsa bu durumda catch calismaz. 
    // ama basina www koydugumuzda fetch üzerine aldigi icin hatayi, bu durumda catch calisir.


    // Hata kontrolü icin iki farkli ihtimal vardir. 
    // Birincisinde promise in ok'i kontrol edilebilir
    // ikincisi ise status kontrolüdür







        //////////////////////////////////////

        /// fetch islemini async ile yapma:
        // bu yöntemde her islem sonucu bir degiskene atilir ve daha sonra islenir

           //// jsondan sonra () yapilir.


    async function usingAsyncFetch(url) {
        try {
            const response = await fetch(url);
            const userData = await response.json();
            if(!response.ok) {
                throw new Error("Something went wrong")
            }

                /// json formati bir object oldugu icin forEach kullanamayiz. o array methodu.
            // for (let i of Object.entries(userData)) {
            //     console.log(i);
            // }
                    // destructuring:
            for (let [key, value] of Object.entries(userData)) {
                console.log(key + " => " + value);
            }
            // for (let i of Object.keys(userData)) {
            //     console.log(i);
            // }
            
        } catch (err) {
            console.log(err);
        }
    };


    usingAsyncFetch(url);













    ////////////////////////////////

    /////////////   2. Method:
    // func icinde hic console.log yok



    async function usingAsyncFetch2(url) {
        try {
            const response = await fetch(url);
            if (!response.ok) {
                throw new Error("Something went wrong");
            }
            return await response.json();
        } catch (err) {
            console.log(err);
        }
    };

    console.log(usingAsyncFetch2(url));

    // bu kod bize pending return  eder. o nedenle bizim birsey yapmamiz lazim.



            /// then li 1. yöntem:

        // asagidaki yöntemde, console.log bir callback func olarak verilir then icerisine. bu nedenle then e ne geldiyse aynisini yazdirir
    // usingAsyncFetch2(url).then(console.log)



            //  then li 2. Yöntem:

        usingAsyncFetch2(url).then((data) => {
            console.log(data);
        });


            ////  async li 3. yöntem:

    // const data = await usingAsyncFetch2(url);
    // bu sekilde yaparsak, hata aliriz. cünkü await sadece async func icinde kullanilir der.

    
    const asyncFunc = async () => {
        const data = await usingAsyncFetch2(url);
        console.log(data);
    };

    asyncFunc();



        /// 4. Yöntem:
        // Bu yöntem de zorda kaldigimizda kullanilabilir. Su an icinde bulundugumuz js dosyasini komple async func icine aliriz. ve hemen cagiririz. böyle bu func icinde yani tüm sayfa icerisine istedigimiz yerde await kullanabiliriz.
        // normal func olarak tanimliyoruz. hemen cagirabilmek icin komple hepsini () icine aliyoruz.
        
        // (async () => {
            /// tüm dosya
        // })();



        /// Cok önemli:
        // addeventlistener da click yazdiktan sonra yazacagimiz func önüne async koyarsak, ondan sonra istedigimiz yerinde await kullanabiliriz.












        //////////////////////////

        //////  todos API:

        const url2 = "https://jsonplaceholder.typicode.com/todos";

        myArrow = async () => {
            let resultTodo = await usingAsyncFetch2(url2);
            console.log(resultTodo);
                // array geldigi icin forEach burada olur
            // resultTodo.forEach((data) => {
            //     console.log(data);
            // })
        };

        myArrow();



            // ayni islemi yukarida tanimladigimiz fonksiyonlardan digeri ile de cagirabiliriz
        usingFetch(url2);



        // async func da promise ile ayni calisma prensibine sahiptir. microtask kuyruguna gider. callstack bosalir bosalmaz isleme alinir.

    // ama cay örneginde bizim tüm then lerimiz birbiri ile iliskili oldugu icin biz tek catch kullandik.

    </script>

</body>
</html>